pc_fiche_autre:
    resource: "@PCFicheBundle/Resources/config/routing/demande/autre.yml"
    prefix:   /autre
    
pc_fiche_avenant:
    resource: "@PCFicheBundle/Resources/config/routing/demande/avenant.yml"
    prefix:   /avenant



pc_fiche_pscati:
    resource: "@PCFicheBundle/Resources/config/routing/demande/pscati.yml"
    prefix:   /pscati

pc_fiche_pifelaboratoire:
    resource: "@PCFicheBundle/Resources/config/routing/demande/pifelaboratoire.yml"
    prefix:   /pifelaboratoire

pc_fiche_pifeclassique:
    resource: "@PCFicheBundle/Resources/config/routing/demande/pifeclassique.yml"
    prefix:   /pifeclassique

pc_fiche_madsalles:
    resource: "@PCFicheBundle/Resources/config/routing/demande/madsalles.yml"
    prefix:   /madsalles

pc_fiche_madevenementgratuit:
    resource: "@PCFicheBundle/Resources/config/routing/demande/madevenementgratuit.yml"
    prefix:   /madevenementgratuit


pc_fiche_chartepartenariat:
    resource: "@PCFicheBundle/Resources/config/routing/demande/chartepartenariat.yml"
    prefix:   /chartepartenariat

demande:
    path:     /
    defaults: { _controller: "PCFicheBundle:Demande:index" }

demande_show:
    path:     /{id}/show
    defaults: { _controller: "PCFicheBundle:Demande:show" }

demande_new:
    path:     /new
    defaults: { _controller: "PCFicheBundle:Demande:new" }

demande_create:
    path:     /create
    defaults: { _controller: "PCFicheBundle:Demande:create" }
    methods:  POST

demande_edit:
    path:     /{id}/edit
    defaults: { _controller: "PCFicheBundle:Demande:edit" }

demande_update:
    path:     /{id}/update
    defaults: { _controller: "PCFicheBundle:Demande:update" }
    methods:  [POST, PUT]

demande_delete:
    path:     /{id}/delete
    defaults: { _controller: "PCFicheBundle:Demande:delete" }
    methods:  [POST, DELETE]
    
demande_choosesubype:
    path:     /{id}/choose
    defaults: { _controller: "PCFicheBundle:Demande:chooseSubType" }
