<?php

namespace Proxies\__CG__\PC\FicheBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Autre extends \PC\FicheBundle\Entity\Autre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PC\\FicheBundle\\Entity\\Autre' . "\0" . 'type', '' . "\0" . 'PC\\FicheBundle\\Entity\\Autre' . "\0" . 'sousType', 'alertes', 'avenants', 'fichiers', 'messages', 'demandeur', 'actions'];
        }

        return ['__isInitialized__', '' . "\0" . 'PC\\FicheBundle\\Entity\\Autre' . "\0" . 'type', '' . "\0" . 'PC\\FicheBundle\\Entity\\Autre' . "\0" . 'sousType', 'alertes', 'avenants', 'fichiers', 'messages', 'demandeur', 'actions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Autre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTemplate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemplate', []);

        return parent::getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(\PC\FicheBundle\Entity\Type $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousType(\PC\FicheBundle\Entity\SousType $sousType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousType', [$sousType]);

        return parent::setSousType($sousType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousType', []);

        return parent::getSousType();
    }

    /**
     * {@inheritDoc}
     */
    public function addAlerte(\PC\FicheBundle\Entity\Alerte $alerte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAlerte', [$alerte]);

        return parent::addAlerte($alerte);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAlerte(\PC\FicheBundle\Entity\Alerte $alerte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAlerte', [$alerte]);

        return parent::removeAlerte($alerte);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlertes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlertes', []);

        return parent::getAlertes();
    }

    /**
     * {@inheritDoc}
     */
    public function addAvenant(\PC\FicheBundle\Entity\Avenant $avenant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAvenant', [$avenant]);

        return parent::addAvenant($avenant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAvenant(\PC\FicheBundle\Entity\Avenant $avenant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAvenant', [$avenant]);

        return parent::removeAvenant($avenant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvenants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvenants', []);

        return parent::getAvenants();
    }

    /**
     * {@inheritDoc}
     */
    public function addFichier(\PC\FicheBundle\Entity\Fichier $fichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFichier', [$fichier]);

        return parent::addFichier($fichier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFichier(\PC\FicheBundle\Entity\Fichier $fichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFichier', [$fichier]);

        return parent::removeFichier($fichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichiers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichiers', []);

        return parent::getFichiers();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessage(\PC\FicheBundle\Entity\FicheMessage $message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessage', [$message]);

        return parent::addMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessage(\PC\FicheBundle\Entity\FicheMessage $message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessage', [$message]);

        return parent::removeMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessages', []);

        return parent::getMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeur(\PC\UserBundle\Entity\User $demandeur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeur', [$demandeur]);

        return parent::setDemandeur($demandeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeur', []);

        return parent::getDemandeur();
    }

    /**
     * {@inheritDoc}
     */
    public function addAction(\PC\FicheBundle\Entity\Action $action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAction', [$action]);

        return parent::addAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAction(\PC\FicheBundle\Entity\Action $action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAction', [$action]);

        return parent::removeAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getActions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActions', []);

        return parent::getActions();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoute', []);

        return parent::getRoute();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoute($route)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoute', [$route]);

        return parent::setRoute($route);
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatDemande($etatDemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatDemande', [$etatDemande]);

        return parent::setEtatDemande($etatDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatDemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatDemande', []);

        return parent::getEtatDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntitule($intitule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntitule', [$intitule]);

        return parent::setIntitule($intitule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntitule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntitule', []);

        return parent::getIntitule();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjet($objet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjet', [$objet]);

        return parent::setObjet($objet);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjet', []);

        return parent::getObjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatConvention($etatConvention)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatConvention', [$etatConvention]);

        return parent::setEtatConvention($etatConvention);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatConvention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatConvention', []);

        return parent::getEtatConvention();
    }

    /**
     * {@inheritDoc}
     */
    public function setCocontractant($cocontractant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCocontractant', [$cocontractant]);

        return parent::setCocontractant($cocontractant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCocontractant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCocontractant', []);

        return parent::getCocontractant();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormeJuridiqueCocontractant($formeJuridiqueCocontractant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormeJuridiqueCocontractant', [$formeJuridiqueCocontractant]);

        return parent::setFormeJuridiqueCocontractant($formeJuridiqueCocontractant);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormeJuridiqueCocontractant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormeJuridiqueCocontractant', []);

        return parent::getFormeJuridiqueCocontractant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseSiege($adresseSiege)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseSiege', [$adresseSiege]);

        return parent::setAdresseSiege($adresseSiege);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseSiege()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseSiege', []);

        return parent::getAdresseSiege();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroSiret($numeroSiret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroSiret', [$numeroSiret]);

        return parent::setNumeroSiret($numeroSiret);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroSiret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroSiret', []);

        return parent::getNumeroSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeApe($codeApe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeApe', [$codeApe]);

        return parent::setCodeApe($codeApe);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeApe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeApe', []);

        return parent::getCodeApe();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreRepresentant($titreRepresentant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreRepresentant', [$titreRepresentant]);

        return parent::setTitreRepresentant($titreRepresentant);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreRepresentant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreRepresentant', []);

        return parent::getTitreRepresentant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomRepresentant($nomRepresentant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomRepresentant', [$nomRepresentant]);

        return parent::setNomRepresentant($nomRepresentant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomRepresentant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomRepresentant', []);

        return parent::getNomRepresentant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomRepresentant($prenomRepresentant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomRepresentant', [$prenomRepresentant]);

        return parent::setPrenomRepresentant($prenomRepresentant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomRepresentant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomRepresentant', []);

        return parent::getPrenomRepresentant();
    }

    /**
     * {@inheritDoc}
     */
    public function setFonctionRepresentant($fonctionRepresentant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFonctionRepresentant', [$fonctionRepresentant]);

        return parent::setFonctionRepresentant($fonctionRepresentant);
    }

    /**
     * {@inheritDoc}
     */
    public function getFonctionRepresentant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFonctionRepresentant', []);

        return parent::getFonctionRepresentant();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeurPolytech($demandeurPolytech)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeurPolytech', [$demandeurPolytech]);

        return parent::setDemandeurPolytech($demandeurPolytech);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeurPolytech()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeurPolytech', []);

        return parent::getDemandeurPolytech();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEffet($dateEffet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEffet', [$dateEffet]);

        return parent::setDateEffet($dateEffet);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEffet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEffet', []);

        return parent::getDateEffet();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEcheance($dateEcheance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEcheance', [$dateEcheance]);

        return parent::setDateEcheance($dateEcheance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEcheance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEcheance', []);

        return parent::getDateEcheance();
    }

    /**
     * {@inheritDoc}
     */
    public function setReconductionTacite($reconductionTacite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReconductionTacite', [$reconductionTacite]);

        return parent::setReconductionTacite($reconductionTacite);
    }

    /**
     * {@inheritDoc}
     */
    public function getReconductionTacite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReconductionTacite', []);

        return parent::getReconductionTacite();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidationJuridique($validationJuridique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidationJuridique', [$validationJuridique]);

        return parent::setValidationJuridique($validationJuridique);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidationJuridique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidationJuridique', []);

        return parent::getValidationJuridique();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidationDirection($validationDirection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidationDirection', [$validationDirection]);

        return parent::setValidationDirection($validationDirection);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidationDirection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidationDirection', []);

        return parent::getValidationDirection();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateValidationJuridique($dateValidationJuridique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateValidationJuridique', [$dateValidationJuridique]);

        return parent::setDateValidationJuridique($dateValidationJuridique);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateValidationJuridique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateValidationJuridique', []);

        return parent::getDateValidationJuridique();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateValidationDirection($dateValidationDirection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateValidationDirection', [$dateValidationDirection]);

        return parent::setDateValidationDirection($dateValidationDirection);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateValidationDirection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateValidationDirection', []);

        return parent::getDateValidationDirection();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignaturePolytech($signaturePolytech)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignaturePolytech', [$signaturePolytech]);

        return parent::setSignaturePolytech($signaturePolytech);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignaturePolytech()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignaturePolytech', []);

        return parent::getSignaturePolytech();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSignaturePolytech($dateSignaturePolytech)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSignaturePolytech', [$dateSignaturePolytech]);

        return parent::setDateSignaturePolytech($dateSignaturePolytech);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSignaturePolytech()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSignaturePolytech', []);

        return parent::getDateSignaturePolytech();
    }

    /**
     * {@inheritDoc}
     */
    public function setActionDemandee($actionDemandee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActionDemandee', [$actionDemandee]);

        return parent::setActionDemandee($actionDemandee);
    }

    /**
     * {@inheritDoc}
     */
    public function getActionDemandee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActionDemandee', []);

        return parent::getActionDemandee();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuiviActionTexte($suiviActionTexte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuiviActionTexte', [$suiviActionTexte]);

        return parent::setSuiviActionTexte($suiviActionTexte);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuiviActionTexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuiviActionTexte', []);

        return parent::getSuiviActionTexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuiviActionDate($suiviActionDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuiviActionDate', [$suiviActionDate]);

        return parent::setSuiviActionDate($suiviActionDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuiviActionDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuiviActionDate', []);

        return parent::getSuiviActionDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservations($observations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservations', [$observations]);

        return parent::setObservations($observations);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservations', []);

        return parent::getObservations();
    }

    /**
     * {@inheritDoc}
     */
    public function setFluxFinancier($fluxFinancier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFluxFinancier', [$fluxFinancier]);

        return parent::setFluxFinancier($fluxFinancier);
    }

    /**
     * {@inheritDoc}
     */
    public function getFluxFinancier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFluxFinancier', []);

        return parent::getFluxFinancier();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservationFonds($reservationFonds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservationFonds', [$reservationFonds]);

        return parent::setReservationFonds($reservationFonds);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationFonds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationFonds', []);

        return parent::getReservationFonds();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateMAJ($dateMAJ)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateMAJ', [$dateMAJ]);

        return parent::setDateMAJ($dateMAJ);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateMAJ()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateMAJ', []);

        return parent::getDateMAJ();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreNouveauxAvenants($nombreNouveauxAvenants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreNouveauxAvenants', [$nombreNouveauxAvenants]);

        return parent::setNombreNouveauxAvenants($nombreNouveauxAvenants);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreNouveauxAvenants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreNouveauxAvenants', []);

        return parent::getNombreNouveauxAvenants();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreNouveauxFichier($nombreNouveauxFichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreNouveauxFichier', [$nombreNouveauxFichier]);

        return parent::setNombreNouveauxFichier($nombreNouveauxFichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreNouveauxFichier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreNouveauxFichier', []);

        return parent::getNombreNouveauxFichier();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectVars()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectVars', []);

        return parent::getObjectVars();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function incrementerNombreNouveauxAvenants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'incrementerNombreNouveauxAvenants', []);

        return parent::incrementerNombreNouveauxAvenants();
    }

}
