pifeclassique:
    path:     /
    defaults: { _controller: "PCFicheBundle:PIFEClassique:index" }

pifeclassique_show:
    path:     /{id}/show
    defaults: { _controller: "PCFicheBundle:PIFEClassique:show" }
    
pifeclassique_export:
    path:     /export
    defaults: { _controller: "PCFicheBundle:PIFEClassique:export" }
    
pifeclassique_new:
    path:     /{id}/new
    defaults: { _controller: "PCFicheBundle:PIFEClassique:new" }

pifeclassique_request:
    path:     /{id}/demande
    defaults: { _controller: "PCFicheBundle:PIFEClassique:request" }

pifeclassique_create:
    path:     /{id}/create
    defaults: { _controller: "PCFicheBundle:PIFEClassique:create" }
    methods:  POST
    
pifeclassique_edit:
    path:     /edit/{id}
    defaults: { _controller: "PCFicheBundle:PIFEClassique:edit" }

pifeclassique_update:
    path:     /{id}/update
    defaults: { _controller: "PCFicheBundle:PIFEClassique:update" }
    methods:  [POST, PUT]

pifeclassique_delete:
    path:     /{id}/delete
    defaults: { _controller: "PCFicheBundle:PIFEClassique:delete" }
    methods:  [POST, DELETE]
    
pifeclassique_showrequest:
    path:     /{id}/showrequest
    defaults: { _controller: "PCFicheBundle:PIFEClassique:showrequest" }

pifeclassique_createrequest:
    path:     /{id}/createrequest
    defaults: { _controller: "PCFicheBundle:PIFEClassique:createRequest" }
    methods:  POST