template:
    path:     /
    defaults: { _controller: "PCFicheBundle:Template:index" }

template_show:
    path:     /{id}/show
    defaults: { _controller: "PCFicheBundle:Template:show" }

template_new:
    path:     /new
    defaults: { _controller: "PCFicheBundle:Template:new" }

template_create:
    path:     /create
    defaults: { _controller: "PCFicheBundle:Template:create" }
    methods:  POST

template_edit:
    path:     /{id}/edit
    defaults: { _controller: "PCFicheBundle:Template:edit" }

template_update:
    path:     /{id}/update
    defaults: { _controller: "PCFicheBundle:Template:update" }
    methods:  [POST, PUT]

template_delete:
    path:     /{id}/delete
    defaults: { _controller: "PCFicheBundle:Template:delete" }
    methods:  [POST, DELETE]

template_pscati :
    path:     /{id}/pscati
    defaults: { _controller: "PCFicheBundle:Template:pscati" }
    