pc_fiche_fiche:
    resource: "@PCFicheBundle/Resources/config/routing/fiche.yml"
    prefix:   /fiche


pc_fiche_demande:
    resource: "@PCFicheBundle/Resources/config/routing/demande.yml"
    prefix:   /demande    
    
pc_user:
    resource: "@PCUserBundle/Resources/config/routing/user.yml"
    prefix:   /user
    

    

  
  

    
