fichemessage_show:
    path:     /{id}/show
    defaults: { _controller: "PCFicheBundle:FicheMessage:show" }

fichemessage_new:
    path:     /{id}/new
    defaults: { _controller: "PCFicheBundle:FicheMessage:new" }

fichemessage_create:
    path:     /create
    defaults: { _controller: "PCFicheBundle:FicheMessage:create" }
    methods:  POST

fichemessage_delete:
    path:     /{id}/delete
    defaults: { _controller: "PCFicheBundle:FicheMessage:delete" }
    methods:  [POST, DELETE]
