<?php

namespace PC\FicheBundle\Entity;

/**
 * AlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMessages()
    {
        return $this->createQueryBuilder()
        ->where('type= message');
    }
    
    public function getAlertes()
    {
        return $this->createQueryBuilder()
        ->where('type != message');
    }
}
