<?php

namespace PC\FicheBundle\Entity;

/**
 * AvenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvenantRepository extends \Doctrine\ORM\EntityRepository
{
}
