<?php

namespace PC\FicheBundle\Entity;

/**
 * ChartePartenariatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChartePartenariatRepository extends \Doctrine\ORM\EntityRepository
{
}
