<?php

namespace PC\FicheBundle\Entity;

/**
 * FicheMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
