<?php

namespace PC\FicheBundle\Entity;

/**
 * MADEvenementGratuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MADEvenementGratuitRepository extends \Doctrine\ORM\EntityRepository
{
}
