<?php

namespace PC\FicheBundle\Entity;

/**
 * MADSallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MADSallesRepository extends \Doctrine\ORM\EntityRepository
{
}
