<?php

namespace PC\FicheBundle\Entity;

/**
 * MappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MappingRepository extends \Doctrine\ORM\EntityRepository
{
}
