<?php

namespace PC\FicheBundle\Entity;

/**
 * PIFEClassiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PIFEClassiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
