<?php

namespace PC\FicheBundle\Entity;

/**
 * PIFELaboratoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PIFELaboratoireRepository extends \Doctrine\ORM\EntityRepository
{
}
