<?php

namespace PC\FicheBundle\Entity;

/**
 * PSCatiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PSCatiRepository extends \Doctrine\ORM\EntityRepository
{
}
