<?php

namespace PC\FicheBundle\Entity;

/**
 * SousTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
